GHC_N_OPTS = ghc --make -XMultiParamTypeClasses -XArrows -XTypeSynonymInstances -XFlexibleInstances -Wall -fno-warn-name-shadowing -fno-warn-unused-matches -fno-warn-type-defaults -outputdir obj


all0: s c

all: yampa glfw s c copyToBin

s:
	$(GHC_N_OPTS) Server.hs

c:
	$(GHC_N_OPTS) Client.hs

ns:
	$(GHC_N_OPTS) NoServer.hs

yampa:
	cd Yampa; cabal install

glfw:
	cabal install GLFW

copyToBin:
	cp Client ../hamBin/; cp Server ../hamBin/

#Makefile is generated by ghc --make so we just delete it
clean:
	rm -r Client Server NoServer obj/

