# DO NOT DELETE: Beginning of Haskell dependencies
ReadImage.o : ReadImage.hs
Sprites.o : Sprites.hs
Sprites.o : ReadImage.hi
WallRender.o : WallRender.hs
WallRender.o : Sprites.hi
TGA.o : TGA.hs
Textures.o : Textures.hs
Textures.o : TGA.hi
TextureFonts.o : TextureFonts.hs
TextureFonts.o : Textures.hi
Vec3d.o : Vec3d.hs
Common.o : Common.hs
Common.o : Vec3d.hi
IdentityList.o : IdentityList.hs
IdentityList.o : Common.hi
BoundingVolume.o : BoundingVolume.hs
BoundingVolume.o : Vec3d.hi
BoundingVolume.o : Common.hi
GameInput.o : GameInput.hs
GameInput.o : Vec3d.hi
GameInput.o : Common.hi
Colors.o : Colors.hs
Terrain.o : Terrain.hs
Terrain.o : BoundingVolume.hi
Terrain.o : Textures.hi
Terrain.o : WallRender.hi
Terrain.o : Colors.hi
Terrain.o : GameInput.hi
Terrain.o : Vec3d.hi
Terrain.o : Common.hi
Render.o : Render.hs
Render.o : Colors.hi
Render.o : Terrain.hi
Render.o : Common.hi
Render.o : Vec3d.hi
TerrainData.o : TerrainData.hs
TerrainData.o : TextureFonts.hi
TerrainData.o : Textures.hi
TerrainData.o : Terrain.hi
TerrainData.o : WallRender.hi
TerrainData.o : Colors.hi
TerrainData.o : GameInput.hi
TerrainData.o : Vec3d.hi
TerrainData.o : Common.hi
Player.o : Player.hs
Player.o : Render.hi
Player.o : Colors.hi
Player.o : TextureFonts.hi
Player.o : TerrainData.hi
Player.o : WallRender.hi
Player.o : GameInput.hi
Player.o : Vec3d.hi
Player.o : Common.hi
Laser.o : Laser.hs
Laser.o : Colors.hi
Laser.o : GameInput.hi
Laser.o : Vec3d.hi
Laser.o : Common.hi
Object.o : Object.hs
Object.o : Render.hi
Object.o : BoundingVolume.hi
Object.o : Vec3d.hi
Object.o : TerrainData.hi
Object.o : Terrain.hi
Object.o : Laser.hi
Object.o : Player.hi
Object.o : GameInput.hi
Object.o : Common.hi
GameCore.o : GameCore.hs
GameCore.o : BoundingVolume.hi
GameCore.o : Common.hi
GameCore.o : GameInput.hi
GameCore.o : Object.hi
GameCore.o : IdentityList.hi
Net.o : Net.hs
Net.o : Laser.hi
Net.o : Player.hi
Net.o : GameInput.hi
Net.o : Common.hi
RunGame.o : RunGame.hs
RunGame.o : Render.hi
RunGame.o : TextureFonts.hi
RunGame.o : Textures.hi
RunGame.o : TerrainData.hi
RunGame.o : Terrain.hi
RunGame.o : Net.hi
RunGame.o : Laser.hi
RunGame.o : IdentityList.hi
RunGame.o : GameCore.hi
RunGame.o : Vec3d.hi
RunGame.o : Object.hi
RunGame.o : GameInput.hi
RunGame.o : Player.hi
RunGame.o : Common.hi
Client.o : Client.hs
Client.o : Net.hi
Client.o : Object.hi
Client.o : Common.hi
Client.o : Terrain.hi
Client.o : RunGame.hi
# DO NOT DELETE: End of Haskell dependencies
