all0: server client copyToBin

all: yampa glfw server client copyToBin

server:
	ghc --make -XMultiParamTypeClasses -XArrows -XTypeSynonymInstances -XFlexibleInstances Server.hs

client:
	ghc --make -XMultiParamTypeClasses -XArrows -XTypeSynonymInstances -XFlexibleInstances Client.hs

yampa:
	cd Yampa; cabal install

glfw:
	cabal install GLFW

copyToBin:
	cp Client ../hamBin/; cp Server ../hamBin/

#Makefile is generated by ghc --make so we just delete it
clean:
	rm *.o *.hi Client Server

