#!/bin/sh

# use this to run individual ghci call nicely. -Harley
# we can adopt this to test other parts separately too.
ghci -XArrows -XMultiParamTypeClasses -XTypeSynonymInstances -XFlexibleInstances -threaded Server2.hs <<HERE
    serverTest
HERE
