#!/bin/sh

# use this to run individual ghci call nicely. -Harley
# we can adopt this to test other parts separately too.
ghci -XArrows -XMultiParamTypeClasses -XPatternSignatures -XTypeSynonymInstances -XFlexibleInstances Main.hs <<HERE
    textureTest
HERE
